
volumes:
  postgres_data:

networks:
  grafanahep:
    driver: bridge

services:
  postgres:
    image: postgres:13
    container_name: container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: container
    ports:
      - "5432:5432"
    networks:
      - grafanahep
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - grafanahep
  