services:
  postgres:
    image: postgres:13
    container_name: container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nodeapp:
    build: .
    container_name: node-container
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: